-- Revert migration 018
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS scanned_codes CASCADE;
DROP TABLE IF EXISTS document_items CASCADE;
DROP TABLE IF EXISTS documents CASCADE;

ALTER TABLE warehouses DROP COLUMN IF EXISTS location;
ALTER TABLE users DROP COLUMN IF EXISTS status;
ALTER TABLE users DROP COLUMN IF EXISTS external_id;
ALTER TABLE devices DROP COLUMN IF EXISTS name;
ALTER TABLE devices DROP COLUMN IF EXISTS last_seen_at;
ALTER TABLE devices DROP COLUMN IF EXISTS created_at;
