ALTER TABLE companies
    ADD COLUMN IF NOT EXISTS cuit_verified_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS razon_social TEXT,
    ADD COLUMN IF NOT EXISTS condicion_iva TEXT,
    ADD COLUMN IF NOT EXISTS domicilio_fiscal TEXT,
    ADD COLUMN IF NOT EXISTS padron_synced_at TIMESTAMPTZ;

COMMENT ON COLUMN companies.condicion_iva IS 'Canonical: RESPONSABLE_INSCRIPTO, MONOTRIBUTO, EXENTO, CONSUMIDOR_FINAL, NO_CATEGORIZADO, DESCONOCIDO.';
